### ISSUE TITLE
Styling root page

### ISSUE THREAD

**Issue by nujovich** [mermelada-tech/advice-generator-app#1]
![image](https://user-images.githubusercontent.com/48018975/224322818-af325ea6-b84a-4512-b384-083f26eaa666.png)

**Comment by Gukirt007** [comment]
do you need help with?

**Comment by amelia2802** [comment]
Hi there @nujovich ,
I'm interested in working on this issue! Before I get started, I have a couple of questions about the design of the root page. What kind of webpage styling are you looking for to resolve the issue? Specifically:

- What are the constraints on the design?
- Are there any design patterns, styles, or themes that the website already uses that I should be aware of?
- If yes, then can you provide any design mockups, wireframes, or prototypes that illustrate the desired design?
- Are there any existing design components or frameworks that I should use?
 
I'm looking forward to working on this issue and creating a design that meets the needs of the project.

**Comment by nujovich** [comment]
Hi @amelia2802 !! glad you can help us. @gi-manzano is our ui/ux and she can provide you with some mockups we made on figma for our website. If that´s ok with you I can assign you the issue

**Comment by amelia2802** [comment]
Great to hear that! Please share the Figma link with me and let me know what specific tasks you would like me to work on. I'm excited to collaborate with @gi-manzano on this project and create a great user experience for your website.

**Comment by gi-manzano** [comment]
hi! @amelia2802  that sounds great, I will share the link to Figma, you can edit it, there is not too much done you can let your creativity go into action as long as you respect the colour style of our branding and looking for a font similar to the one in the Figma. If this sounds good to you, you can start.

**Comment by gi-manzano** [comment]
@amelia2802 https://www.figma.com/file/ZKMjD0X15XKCBR4G5tJ72n/WEB-DESIGN?node-id=0%3A1&t=8nCto9F4dang3rks-1 if you need to ask me something you can contact me!!!

**Comment by amelia2802** [comment]
> @amelia2802 https://www.figma.com/file/ZKMjD0X15XKCBR4G5tJ72n/WEB-DESIGN?node-id=0%3A1&t=8nCto9F4dang3rks-1 if you need to ask me something you can contact me!!!

Great! I will work on this and let you know if I need more clarification and feedback.

**Comment by amelia2802** [comment]
Hello @gi-manzano , I'm working on this issue, and here's my progress report.

#### Progress Report
- Created Header, Body+Animation Components.
- Made Web Responsive each of the components
#### Preview
[Advice Generator App.webm](https://user-images.githubusercontent.com/49182604/226198942-fb960ee2-1716-4fae-9b7d-4ee19090b724.webm)

#### Feedback
- Do I need to modify/add anything?
- ![figma](https://user-images.githubusercontent.com/49182604/226199311-b3f3b400-6c8c-4689-b18e-aaad4f35772f.jpg)
- Can you clarify what this section will be used for? What are the Rectangle and Square boxes?
- Can you share the font used in this picture?
![figma 2](https://user-images.githubusercontent.com/49182604/226199688-cbffdd45-6d95-475b-aaed-d1523eded0ee.jpg)
- Can you share the logo?

**Comment by gi-manzano** [comment]
hi! @amelia2802 Hey, very good advances, I really liked the animation effect, we can remove the rectangular boxes, I had thought of them at first to tell the story of our community but it is not necessary to do it for this challenge, I will share the logo in Figma.
From this link, you can download the font used on the cover https://www.dafont.com/a-day-without-sun.font
For images, you could implement presenting them in some circular shape, or with 40° angles with a shadow effect at the bottom so they don't lie flat.✨☺

**Comment by amelia2802** [comment]
> For images, you could implement presenting them in some circular shape, or with 40° angles with a shadow effect at the bottom so they don't lie flat.✨☺

Sure!

**Comment by amelia2802** [comment]
Hi @gi-manzano can you review the PR?
